version: '3.8'

services:
  db:
    image: postgres:15
    container_name: epicrapedia_postgres
    restart: always
    environment:
      POSTGRES_DB: epicrapedia
      POSTGRES_USER: epicrapedia
      POSTGRES_PASSWORD: epicrapedia
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 2s
      retries: 10

  api:
    build: .
    container_name: epicrapedia_postgres_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/epicrapedia
      SPRING_DATASOURCE_USERNAME: epicrapedia
      SPRING_DATASOURCE_PASSWORD: epicrapedia
    depends_on:
      db:
        condition: service_healthy


volumes:
  pgdata:
